/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ChatMessage {
  'id' : string,
  'timestamp' : Time,
  'botResponse' : string,
  'customerQuery' : string,
}
export interface Customer {
  'id' : string,
  'name' : string,
  'joinedAt' : Time,
  'email' : string,
  'sessionToken' : [] | [string],
  'passwordHash' : string,
  'phone' : string,
}
export interface Medicine {
  'id' : string,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export type RegisterCustomerResult = { 'ok' : null } |
  { 'emailAlreadyExists' : null } |
  { 'internalError' : null };
export type RegisterSellerResult = { 'ok' : null } |
  { 'emailAlreadyExists' : null } |
  { 'internalError' : null };
export interface SellerAccount {
  'id' : string,
  'status' : SellerStatus,
  'name' : string,
  'joinedAt' : Time,
  'whatsapp' : string,
  'email' : string,
  'address' : string,
  'sessionToken' : [] | [string],
  'licenseNumber' : string,
  'passwordHash' : string,
  'phone' : string,
}
export type SellerStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'inactive' : null };
export interface SiteContent { 'key' : string, 'value' : string }
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[ChatMessage], undefined>,
  'addMedicine' : ActorMethod<[Medicine], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'customerLogin' : ActorMethod<[string, string], [] | [string]>,
  'deleteMedicine' : ActorMethod<[string], undefined>,
  'deleteSeller' : ActorMethod<[string], undefined>,
  'getActiveSellers' : ActorMethod<[], Array<SellerAccount>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessage' : ActorMethod<[string], ChatMessage>,
  'getCustomerByToken' : ActorMethod<[string], [] | [Customer]>,
  'getMedicine' : ActorMethod<[string], Medicine>,
  'getSellerByToken' : ActorMethod<[string], [] | [SellerAccount]>,
  'getSiteContent' : ActorMethod<[string], SiteContent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'logoutCustomer' : ActorMethod<[string], boolean>,
  'logoutSeller' : ActorMethod<[string], boolean>,
  'registerCustomer' : ActorMethod<
    [string, string, string, string],
    RegisterCustomerResult
  >,
  'registerSeller' : ActorMethod<
    [string, string, string, string, string, string, string],
    RegisterSellerResult
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sellerLogin' : ActorMethod<[string, string], [] | [string]>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateMedicine' : ActorMethod<[string, Medicine], undefined>,
  'updateSeller' : ActorMethod<[string, SellerAccount], undefined>,
  'updateSiteContent' : ActorMethod<[SiteContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];