/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'timestamp' : IDL.Nat,
  'botResponse' : IDL.Text,
  'customerQuery' : IDL.Text,
});
export const Medicine = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Seller = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : IDL.Nat,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'phone' : IDL.Text,
});
export const SiteContent = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });

export const idlService = IDL.Service({
  'addChatMessage' : IDL.Func([ChatMessage], [], []),
  'addMedicine' : IDL.Func([Medicine], [], []),
  'addSeller' : IDL.Func([Seller], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteMedicine' : IDL.Func([IDL.Text], [], []),
  'deleteSeller' : IDL.Func([IDL.Text], [], []),
  'getActiveSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
  'getChatMessage' : IDL.Func([IDL.Text], [ChatMessage], ['query']),
  'getMedicine' : IDL.Func([IDL.Text], [Medicine], ['query']),
  'getSeller' : IDL.Func([IDL.Text], [Seller], ['query']),
  'getSiteContent' : IDL.Func([IDL.Text], [SiteContent], ['query']),
  'updateMedicine' : IDL.Func([IDL.Text, Medicine], [], []),
  'updateSeller' : IDL.Func([IDL.Text, Seller], [], []),
  'updateSiteContent' : IDL.Func([SiteContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'timestamp' : IDL.Nat,
    'botResponse' : IDL.Text,
    'customerQuery' : IDL.Text,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Seller = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : IDL.Nat,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SiteContent = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  
  return IDL.Service({
    'addChatMessage' : IDL.Func([ChatMessage], [], []),
    'addMedicine' : IDL.Func([Medicine], [], []),
    'addSeller' : IDL.Func([Seller], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteMedicine' : IDL.Func([IDL.Text], [], []),
    'deleteSeller' : IDL.Func([IDL.Text], [], []),
    'getActiveSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
    'getChatMessage' : IDL.Func([IDL.Text], [ChatMessage], ['query']),
    'getMedicine' : IDL.Func([IDL.Text], [Medicine], ['query']),
    'getSeller' : IDL.Func([IDL.Text], [Seller], ['query']),
    'getSiteContent' : IDL.Func([IDL.Text], [SiteContent], ['query']),
    'updateMedicine' : IDL.Func([IDL.Text, Medicine], [], []),
    'updateSeller' : IDL.Func([IDL.Text, Seller], [], []),
    'updateSiteContent' : IDL.Func([SiteContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };