/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : string,
  'timestamp' : bigint,
  'botResponse' : string,
  'customerQuery' : string,
}
export interface Medicine {
  'id' : string,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface Seller {
  'id' : string,
  'status' : string,
  'name' : string,
  'joinedAt' : bigint,
  'whatsapp' : string,
  'email' : string,
  'address' : string,
  'licenseNumber' : string,
  'phone' : string,
}
export interface SiteContent { 'key' : string, 'value' : string }
export interface _SERVICE {
  'addChatMessage' : ActorMethod<[ChatMessage], undefined>,
  'addMedicine' : ActorMethod<[Medicine], undefined>,
  'addSeller' : ActorMethod<[Seller], undefined>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'deleteMedicine' : ActorMethod<[string], undefined>,
  'deleteSeller' : ActorMethod<[string], undefined>,
  'getActiveSellers' : ActorMethod<[], Array<Seller>>,
  'getChatMessage' : ActorMethod<[string], ChatMessage>,
  'getMedicine' : ActorMethod<[string], Medicine>,
  'getSeller' : ActorMethod<[string], Seller>,
  'getSiteContent' : ActorMethod<[string], SiteContent>,
  'updateMedicine' : ActorMethod<[string, Medicine], undefined>,
  'updateSeller' : ActorMethod<[string, Seller], undefined>,
  'updateSiteContent' : ActorMethod<[SiteContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];